### ISSUE TITLE
Front-end/client App Features Overview

### ISSUE THREAD

**Issue by elwinschmitz** [rodekruis/cash-program-design-wizard#28]
This issue can act as a sort of "Epic" (in Scrum terms) to keep an overview of all separate GitHub Issues related to the front-end/client app.
This message can list all possible/future features, before we create specific issues for building them. So we can use this as a log of the refinement of "what feature needs to be in the app".

---

# MVP

See Milestone: [Get Ready for User Acceptance Test](https://github.com/rodekruis/cash-program-design-wizard/milestone/1)

## MVP | User Features
Things a user can see/do/use.

- [x] Start - Landing-page: [/home](https://orange-grass-0aefaa103.azurestaticapps.net/home)
- [x] Login-page: #56

### MVP | App UI
- [x] AppHeader: #33
  - [x] UserState-component - with username/email + logout
  - [x] ConnectivityStatus-component + "go on/off-line" toggle(s) #226
- [x] Sidebar + collapsable-toggle - placeholder only for now
- [x] ProgramPhases: #58 - placeholder only for now

### MVP | Home/Start/Login page
- [x] Home page (for demo/debugging)
- [x] Log-in link
- [x] On successful log-in, redirect to `/program`

### MVP | Program detail/page
- [x] Redirect to users' Program-Id
  When no ProgramId is provided, get the assigned programId (from the back-end) and redirect to the Program-detail-page
- [x] Program-page:
  - [x] #30
  - [x] #54 
- [x] #57
  - [x] Filter visible questions when a Tag is set #227
- [x] QuestionSection:
  - [x]  #94
  - [x] Section deep-links, see: [comment](https://github.com/rodekruis/cash-program-design-wizard/issues/28#issuecomment-910402696)
  - [x] SubSections #176 
  - [x] Input Validation(s) + Feedback for QuestionInputs #228
  - [x] Edit-features only for 'edit'-users #239 
  - [x] Comments:
    - [x] (For Edit-role) "CommentInput"-component #229
    - [x] Show Comment/Conversation-component (with author+date display) #230
    - [x] Style/layout longer conversations #231
- [x] Nav-Progress:
  - [x]  #112
  - [x] Save Answers of activeSection #111 
  - [x] Put (duplicate? or fixed?) set of buttons on top of QuestionSection #232
  - [x] Show/Save Answers of "select-1/N"-type Questions #233

### MVP | Report-page
- [x] Report-page: #55
- [x] Data-model/structure?
- [x] Answers:
  - [x] type: only inputs/values #132
  - [x] type: narrative/fill-in/template #235
- [x] Optimize layout/styling for print (hide App-UI etc) #234

## MVP | Connectivity / Offline
- [x] Service-worker for basic offline-support #50
- [x] Set-up API-request(s) queue #236 
- [x] Manually trigger "go offline" or "go online" sync processes #237

## MVP | Structural features / plumbing
- [ ] Production environments: #2
  - [x] #32
- [x] StateService: #29
- [x] Translations (supporting RTL) #49
- [x] Users / Authentication #109
  - [x] AuthGuards / authentication for (some) routes
- [x] Static mock-data (on hard-coded Program-Id: "123")

---

# v1

After the acceptance-test, there will be some additions or bug-fixes towards a `v1` version of the product.

See Milestone: [Delivery of MVP/v1](https://github.com/rodekruis/cash-program-design-wizard/milestone/2)

---

# v2 Later improvements/enhancements/nice-to-haves...

## v2 | App UI
- [ ] LanguageSwitcher-component
- [ ] Side-bar collapsible
- [ ] Tooltip ℹ️ component
- [ ] Custom App icons (also in PWA-manifest etc) #85 

### v2 | Home/Start/Login page
- [x] (before login) Home-page introduction/explanation text/video?
- [x] (after login) auto-redirect `/home` to `/program`?

### v2 | Program page
- [ ] Handle "Program Not Found"-flow (also for Report-page) #225 

### v2 | Report page
- [ ] Generate + download PDF-file (client-side)

## v2 | Connectivity / Offline
- [x] Connectivity-Notifications (async) (See #357)
  - [x] Show connectivity-status changes - "You seem to have gone offline. Don't worry, you can continue working..."
  - [ ] Show Progress of API-requests-queue

## v2 | Other topics
- Testing
  - Unit-tests - Using Jasmine, per Component/Service/Page
  - Integration tests (Using https://Cypress.io?)
- Monitoring / Telemetry #87

**Comment by elwinschmitz** [comment]
A possible future feature:

### Program-page: Section deep-linking

Like: `/program/1/financial-details?topic=cash`
So this would set the "activeSection" automatically to the one with that slug. And set the filter automatically to "cash".

Or: `/program/1/overview/project-objective` (With an extra level)
We could 'fake' this by hard-coding the parent-section into the slug.

**Comment by elwinschmitz** [comment]
### Plumbing...

Possibly we want to use "PubSub"-bases event-logic to trigger different things in the UI.
Here are some links related to the concept and/or possible packages to use:
- https://betterprogramming.pub/observer-vs-pub-sub-pattern-50d3b27f838c
- https://www.npmjs.com/package/@pscoped/ngx-pub-sub
- https://www.npmjs.com/package/angular7-pubsub

Also:
> "**Request**", "**Will**" and "**Did**". These are arbitrarilly chosen to impose some extra structure.
> - "**Request**" denotes intent to perform an action, it is not guaranteed that the action will execute as there might be conditions preventing it (eg unitialized or still loading objects).
> - "**Will**" means that the conditions passed and we are attempting to perform the action.
> - "**Did**" means that the action just got performed.
>
> From: https://audiomass.co/about.html

**Comment by elwinschmitz** [comment]
## PWA related reading
- See more links in: #85 
- https://firt.dev/tags/pwa/
