### ISSUE TITLE
Back-end/server API Features Overview

### ISSUE THREAD

**Issue by elwinschmitz** [rodekruis/cash-program-design-wizard#31]
This issue can act as a sort of "Epic" (in Scrum terms) to keep an overview of all separate GitHub Issues related to the back-end/server app.
This message can list all possible/future features, before we create specific issues for building them. So we can use this as a log/refinement of "what feature needs to be in the API".

## Structural features/plumbing etc
- [ ] Production/staging environments: #2
- [x] App skeleton/scaffolding #9 
- [x] Data storage
  - [x] #5
  - [x] #6 
- [ ] ...

## Generic topics
- [ ] Testing
- [ ] Monitoring / Telemetry - Using ApplicationInsights?

## API features/endpoints
- [x] /api - "hello world!"
- [ ] /health - to check database-connection etc
- [x] /script
  - [x] /scripts/reset - reset the database
- [ ] /users
  - [x] /users/new
  - [x] /users/login
  - [ ] /users/delete
  - [ ] /users/change-password (or `PUT` to `/user/{id}`?)
- [x] Authentication / Roles handling: #41 
  - via Header/Cookie/token etc.
- [ ] /program
  - [ ] `POST /program` - Create a new program
  - [ ] `GET /program/{id}` - 
  - [ ] `PUT /program/{id}` - Update existing values
  - [ ] ...
