### ISSUE TITLE
Set-up Report-page

### ISSUE THREAD

**Issue by elwinschmitz** [rodekruis/cash-program-design-wizard#55]
## ToDo
- [x] Create new page (as sibling of ProgramPage)
- [x] URL as 'child', like: `/program/:id/report` (?)
- [x] Add link to /home
- [x] Page-layout:
  - [x] App-header
  - [x] ProgramPhase-placeholder
  - [x] Sidebar-placeholder
  - [x] (empty) content-area
